---
title: "R Notebook"
output: html_notebook
---


```{r}
rm(list=ls())
library(plm)
library(dplyr)
data = read.csv("EventDataQuarterConc2Tenths.csv")
#data1 = read.csv("EventDataQuarter.csv")

data$yearQuarter = paste0(data$YEAR,"Q",data$QUARTER)
data$yearQuarterState = paste(data$yearQuarter,data$STATEFIP)
data$yearQuarterWage = paste(data$yearQuarter,data$WAGE_BIN)
#data$REAL_MW = data$MW / data$CPI_FACTOR
data$NextChange = data$NextMW / data$CPI_FACTOR - data$RealMW
data$NextChangePct = data$NextChange / data$RealMW
#data$NextChangePct = (data$NextMW - data$RealMW) / data$RealMW
data$DIST_YEAR[data$DIST_YEAR == -250] = -999
data$ActiveChangePct = data$LastChangePct
data$ActiveChangePct[data$DIST<0] = data$NextChangePct[data$DIST<0]
data$ActiveChangePct[data$DIST==-999] = 0
between = dplyr::between
```

```{r}
# Figure 5 approach:
# Find usable events
#   Find usable controls

events = c()
for(state in unique(data$STATEFIP)){
  checkData = filter(data, STATEFIP == state, WAGE_BIN==0)
}

```


```{r}
formula = as.formula("EMP_RATE ~ as.factor(DIST_YEAR):as.factor(WAGE_BIN):ActiveChangePct + as.factor(WAGE_BIN) + as.factor(STATEFIP) + as.factor(YEAR)")
temp = aggregate(EMP_RATE~YEAR+QUARTER+STATEFIP+DIST_YEAR+WAGE_BIN+ActiveChangePct,data=filter(data,between(COMP_Q,0,0.1)), FUN=sum)
reg = lm(formula, data=temp)
#reg = lm(formula, data=filter(data, COMP_Q == 0.9))
coef = summary(reg)$coef


library(stringi)

coefk = function(k){
  yeark = rownames(coef)
  yeark = yeark[stri_detect_fixed(yeark,paste0("(DIST_YEAR)",k))]
  coek = data.frame(coef[rownames(coef) %in% yeark,])
  return(coek)
}

effects = 1/3*(coefk(1)$Estimate + coefk(2)$Estimate + coefk(3)$Estimate) - coefk(0)$Estimate
#effects = coefk(-1)$Estimate -coefk(-2)$Estimate
# std = sqrt(1/9*(coefk(3)$Std..Error**2 +coefk(2)$Std..Error**2 + coefk(1)$Std..Error**2)+ coefk(0)$Std..Error**2)
# std = sqrt(sum(std**2))
# need to use covariance matrix for standard errors (will be messy)

barplot(effects)
abline(h=sum(effects),col="blue")
abline(h=0)
lines(cumsum(effects))
# abline(h=sum(effects)-std, col="red")
# abline(h=sum(effects)+std,col="red")
 

```

```{r}
library(stringi)
formula = as.formula("EMP_RATE_SUB ~ as.factor(DIST_YEAR):as.factor(WAGE_BIN):ActiveChangePct + as.factor(STATEFIP) + as.factor(YEAR)")
for(q in (0:4)/5){
  temp = aggregate(EMP_RATE_SUB~YEAR+QUARTER+STATEFIP+DIST_YEAR+WAGE_BIN+ActiveChangePct,data=filter(data,COMP_Q==q), FUN=sum)
  reg = lm(formula, data=temp)
  #reg = lm(formula, data=filter(data, COMP_Q == 0.9))
  coef = summary(reg)$coef
  
  coefk = function(k){
    yeark = rownames(coef)
    yeark = yeark[stri_detect_fixed(yeark,paste0("(DIST_YEAR)",k))]
    coek = data.frame(coef[rownames(coef) %in% yeark,])
    return(coek)
  }
  
  effects = 1/3*(coefk(1)$Estimate + coefk(2)$Estimate + coefk(3)$Estimate) - coefk(0)$Estimate
  
  barplot(effects,main=q)
  abline(h=sum(effects),col="blue")
  abline(h=0)
  lines(cumsum(effects))
}

 
```

```{r}
# All:
library(stringi)
formula = as.formula("EMP_RATE ~ as.factor(DIST_YEAR):as.factor(WAGE_BIN):ActiveChangePct + as.factor(STATEFIP) + as.factor(YEAR)")
temp = aggregate(EMP_RATE~YEAR+QUARTER+STATEFIP+DIST_YEAR+WAGE_BIN+ActiveChangePct,data=data, FUN=sum)
reg = lm(formula, data=temp)
coef = summary(reg)$coef
  
coefk = function(k){
  yeark = rownames(coef)
  yeark = yeark[stri_detect_fixed(yeark,paste0("(DIST_YEAR)",k))]
  coek = data.frame(coef[rownames(coef) %in% yeark,])
  return(coek)
}

effects = 1/3*(coefk(1)$Estimate + coefk(2)$Estimate + coefk(3)$Estimate) - coefk(0)$Estimate
#effects = coefk(3)$Estimate - coefk(0)$Estimate

barplot(effects)
abline(h=sum(effects),col="blue")
abline(h=0)
lines(cumsum(effects))

```


```{r}
# Simple:
aggData = aggregate(empW ~ POPULATION + TOTAL_HOURS + STATEFIP + QUARTER + YEAR + REAL_MW + DIST_YEAR, data=data, FUN=sum)
regSimple = lm(empW/POPULATION ~ POPULATION + as.factor(STATEFIP) + as.factor(YEAR) + REAL_MW,data=aggData)
summary(regSimple)
```


```{r}
data = pdata.frame(data, index=c("STATE","WAGE_BIN"))
#month, wagebin

formula = as.formula("EMP_RATE ~ as.factor(DIST_YEAR):as.factor(WAGE_BIN)")
reg.fixed = plm(formula, data=data, model="within", effect="twoways")
summary(reg.fixed)
#fixef(reg.fixed)
```


```{r}
#Concentration at state level:
EES = read.csv("EES State.csv")
EES = EES[c(9,15,16,19,21,25)]
EES[is.na(EES$EES),"EES"] = 0
colnames(EES) = c("AGE","YEAR","QUARTER","GEOGRAPHY","INDUSTRY","EES")

ENFullQ = read.csv("ENFullQ State.csv")
ENFullQ = ENFullQ[c(4,6,9,15,16,18)]
ENFullQ[is.na(ENFullQ$ENFullQ) | ENFullQ$ENFullQ == 0,"ENFullQ"]=1
colnames(ENFullQ) = c("GEOGRAPHY","INDUSTRY","AGE","YEAR","QUARTER","ENFullQ")

conc = merge(EES, ENFullQ)
conc$COMPETITION = conc$EES / conc$ENFullQ
write.csv(conc, "Concentration State.csv",row.names=F)
```


New approach: individual level
```{r}
rm(list=ls())
library(plm)
library(stargazer)
data = read.csv("IndividualDataConc2Tenths.csv")
data$RealMW = data$MW / data$CPI_FACTOR
data$DIST_YEAR = floor(data$DIST/4)
data$DIST_YEAR[data$DIST_YEAR == 249] = -999
data$EMP_RATE = data$empW / data$POPULATION
data$EMP_RATE_SUB = data$empW / data$POPULATION_SUB
data$EMP_RATE_SUB[is.na(data$EMP_RATE_SUB)] = 0

data = data[!(colnames(data) %in% c("DIST_F","DIST_B","NextMW"))]
data = data[data$DIST_YEAR > -100,]
data$DIST_YEAR[data$DIST_YEAR == -1] = -999

dataAgg = aggregate(empW ~ YEAR + QUARTER + STATE + POPULATION + RealMW + DIST + DIST_YEAR, data=data, FUN=sum)
dataAgg$empRate = dataAgg$empW / dataAgg$POPULATION

dataAgg2 = aggregate(empW ~ YEAR + QUARTER + STATE + COMP_Q + POPULATION_SUB + POPULATION + RealMW + DIST + DIST_YEAR, data=data, FUN=sum)
dataAgg2$empRate = dataAgg2$empW / dataAgg2$POPULATION
dataAgg2$empRate_Sub = dataAgg2$empW / dataAgg2$POPULATION_SUB

controlData = read.csv("ControlData.csv")

controlData = controlData[!grepl("Sep",colnames(controlData))]
```

```{r}
colnames(controlData)[colnames(controlData) %in% c("geography","industry","agegrp","year","quarter")] = c("GEOGRAPHY","INDUSTRY","AGEGRP","YEAR","QUARTER")
vars = colnames(controlData)[(6:length(colnames(controlData)))]
labels = colnames(controlData)[(1:3)]

# Create lagged values instead of present values
controlData$QUARTER = controlData$QUARTER + 1
controlData$YEAR[controlData$QUARTER==5] = controlData$YEAR[controlData$QUARTER==5] + 1
controlData$QUARTER[controlData$QUARTER==5] = 1


data$GEOGRAPHY = data$METFIPS
data$GEOGRAPHY[data$GEOGRAPHY > 60] = data$STATEFIP[data$GEOGRAPHY > 60]

totalData = merge(data, controlData,all.x=T)
keeps = c()
for(v in colnames(totalData)){
  if(!sum(is.na(totalData[v]))){
    keeps = c(keeps,v)
  }
}
totalData = totalData[keeps]
data = totalData

# for aggregated data
totalData = merge(dataAgg, controlData[controlData$INDUSTRY=="00" & controlData$AGEGRP=="A00",],all.x=T)
keeps = c()
for(v in colnames(totalData)){
  if(!sum(is.na(totalData[v]))){
    keeps = c(keeps,v)
  }
}
totalData = totalData[keeps]
dataAgg = totalData

# agg 2
totalData = merge(dataAgg2, controlData[controlData$INDUSTRY=="00" & controlData$AGEGRP=="A00",],all.x=T)
keeps = c()
for(v in colnames(totalData)){
  if(!sum(is.na(totalData[v]))){
    keeps = c(keeps,v)
  }
}
totalData = totalData[keeps]
dataAgg2 = totalData

rm(controlData)

logControls = c("POPULATION","POPULATION_SUB",colnames(data)[(42:dim(data)[2])])
logControls = logControls[!(logControls %in% c("MHire","POPULATION","ENPersist"))] #from VIF testing below
otherControls = c("AGE","as.factor(INDUSTRY)")
for(v in logControls){
  data[v] = log(data[v] + min(1,min(data[v][data[v]>0])))
}
```



```{r}
formula1C = formula(paste("log(empW+1) ~ log(RealMW) + as.factor(STATE) + as.factor(YEAR) + AGE + as.factor(INDUSTRY)",paste(logControls,collapse="+"),sep="+"))

reg1 = lm(log(empW+1) ~ log(RealMW) + as.factor(STATE) + as.factor(YEAR), data=data)
reg1C = lm(formula1C,data=data)
#  log(COMPETITION+0.001) + log(RealMW):log(COMPETITION+0.001) + 
coef = summary(reg1)$coef
coef = coef[rownames(coef) %in% c("log(RealMW)","log(RealMW):log(COMPETITION + 0.001)"),]
print(coef)
coef = summary(reg1C)$coef
coef = coef[rownames(coef) %in% c("log(RealMW)","log(RealMW):log(COMPETITION + 0.001)"),]
print(coef)

# Add competition:
formula2C = formula(paste("log(empW+1) ~ log(RealMW) + log(COMPETITION+0.001) + log(RealMW):log(COMPETITION+0.001) + as.factor(STATE) + as.factor(YEAR) + AGE + as.factor(INDUSTRY)",paste(logControls,collapse="+"),sep="+"))
reg2 = lm(log(empW+1) ~ log(RealMW) + log(COMPETITION+0.001) + log(RealMW):log(COMPETITION+0.001) + as.factor(STATE) + as.factor(YEAR), data=data)
reg2C = lm(formula2C, data=data)
coef = summary(reg2)$coef
coef = coef[rownames(coef) %in% c("log(RealMW)","log(RealMW):log(COMPETITION + 0.001)"),]
print(coef)
coef = summary(reg2C)$coef
coef = coef[rownames(coef) %in% c("log(RealMW)","log(RealMW):log(COMPETITION + 0.001)"),]
print(coef)


# for(v in logControls){
#   print(cor(data[v],log(data$R)))
#   print(cor(data[v],log(data$ENSep+1)))
#   
# }
# library(car)
# controlsV = logControls[!(logControls %in% c("MHire","POPULATION","ENPersist"))]
# formula2C = formula(paste("log(empW+1) ~ log(RealMW) + log(COMPETITION+0.001) + log(RealMW):log(COMPETITION+0.001) + as.factor(STATE) + as.factor(YEAR) + AGE + as.factor(INDUSTRY)",paste(controlsV,collapse="+"),sep="+"))
# reg2C = lm(formula2C, data=data)
# coef = summary(reg2C)$coef
# coef = coef[rownames(coef) %in% c("log(RealMW)","log(RealMW):log(COMPETITION + 0.001)"),]
# print(coef)
# 
# v = vif(reg2C)
# print(v)
#barplot(v, main="Variance Inflation Factors (Pre-Correction)")


#stargazer(reg1,reg1C,reg2,reg2C,type="text", keep=c(1,2,71,72))
```


```{r}
# Efficient redesign:
reg1 = lm(empW ~ as.factor(DIST_YEAR) + as.factor(DIST_YEAR):log(COMPETITION+0.001) + log(COMPETITION+0.001) + as.factor(STATE) + as.factor(YEAR), data=data)
reg1c = 
```


```{r}
logControlsD = c("POPULATION",colnames(dataAgg)[(13:dim(dataAgg)[2])])
logControlsD = logControlsD[!(logControlsD %in% c("MHire","ENPersist"))] #from VIF testing
for(v in logControlsD){
  dataAgg[v] = log(dataAgg[v] + min(1,min(dataAgg[v][dataAgg[v]>0])))
}
logControlsD2 = c("POPULATION_SUB",colnames(dataAgg2)[(15:dim(dataAgg2)[2])])
logControlsD2 = logControlsD2[!(logControlsD2 %in% c("MHire","ENPersist"))] #from VIF testing
for(v in logControlsD2){
  dataAgg2[v] = log(dataAgg2[v] + min(1,min(dataAgg2[v][dataAgg2[v]>0])))
}



# EMP_RATE_SUB doesn't work too well here, significant effects
# EMP_RATE has sig positive effects 
# log(empW+1) significant all, negative only after
# empW significant 1+, negative
#dep1 = C("EMP_RATE_SUB","EMP_RATE","log(empW+1)","empW")
#formula1 = "as.factor(DIST_YEAR) + as.factor(DIST_YEAR):log(COMPETITION+0.001) + log(COMPETITION+0.001) + as.factor(STATE) + as.factor(YEAR)"
#reg1 = paste0("empW","~",formula1,data=data)
formula1DC = formula(paste("empW ~ as.factor(DIST_YEAR) + as.factor(DIST_YEAR):log(COMPETITION+0.001)+log(COMPETITION+0.001)+as.factor(STATE)+as.factor(YEAR) + AGE + as.factor(INDUSTRY)",paste(logControls,collapse="+"),sep="+"))

reg1D = lm(empW ~ as.factor(DIST_YEAR) + as.factor(DIST_YEAR):log(COMPETITION+0.001) + log(COMPETITION+0.001) + as.factor(STATE) + as.factor(YEAR), data=data)
reg1DC = lm(formula1DC, data=data)
coef = summary(reg1D)$coef
coef = coef[grepl(":log(COMP",rownames(coef),fixed=T),]
print(coef)
coef = summary(reg1DC)$coef
coef = coef[grepl(":log(COMP",rownames(coef),fixed=T),]
print(coef)




# EMP_RATE_SUB not great, mixed effects
# EMP_RATE little effect before, significant positive after
# log(empW+1) only significant for -3,3
# empW previous significant, 0+ not
formula2DC = formula(paste("log(empW+1) ~ as.factor(DIST_YEAR) +as.factor(STATE)+as.factor(YEAR) + AGE + as.factor(INDUSTRY)",paste(logControls,collapse="+"),sep="+"))
reg2D = lm(log(empW+1) ~ as.factor(DIST_YEAR) + as.factor(STATE) + as.factor(YEAR), data=data)
reg2DC = lm(formula2DC,data=data)
coef = summary(reg2D)$coef
coef = coef[grepl("DIST_YEAR",rownames(coef),fixed=T),]
print(coef)
coef = summary(reg2DC)$coef
coef = coef[grepl("DIST_YEAR",rownames(coef),fixed=T),]
print(coef)

# empRate works very well here
# log(empW + 1) also good here
# empW significant only for -3
formula3DC = formula(paste("log(empW+1) ~ as.factor(DIST_YEAR) +as.factor(STATE)+as.factor(YEAR)",paste(logControlsD,collapse="+"),sep="+"))
reg3D = lm(log(empW+1) ~ as.factor(DIST_YEAR) + as.factor(STATE) + as.factor(YEAR), data=dataAgg)
reg3DC = lm(formula3DC,data=dataAgg)
coef = summary(reg3D)$coef
coef = coef[grepl("DIST_YEAR",rownames(coef),fixed=T),]
print(coef)
coef = summary(reg3DC)$coef
coef = coef[grepl("DIST_YEAR",rownames(coef),fixed=T),]
print(coef)


# empRate not great, little significance
# empRate_Sub not great here either
# log(empW+1) weird
# empW best so far, insignificant everywhere but decrease after event in 0.9
formula4DC = formula(paste("empW ~ as.factor(DIST_YEAR) + as.factor(DIST_YEAR):as.factor(COMP_Q) + as.factor(COMP_Q) +as.factor(STATE)+as.factor(YEAR)",paste(logControlsD2,collapse="+"),sep="+"))
reg4D = lm(empW~as.factor(DIST_YEAR)+as.factor(DIST_YEAR):as.factor(COMP_Q)+as.factor(COMP_Q)+as.factor(STATE)+as.factor(YEAR),data=dataAgg2)
reg4DC = lm(formula4DC,data=dataAgg2)
coef = summary(reg4D)$coef
coef = coef[grepl(":",rownames(coef),fixed=T),]
print(coef)
coef = summary(reg4DC)$coef
coef = coef[grepl(":",rownames(coef),fixed=T),]
print(coef)

```

Add controls:
```{r}
# ADD CONTROLS:

# empW all sig but 0, all negative
# EMP_RATE 1+ sig positive
# EMP_RATE_SUB 1+ sig and neg
# log(empW+1) 0+ sign and neg
reg = lm(log(empW+1) ~ as.factor(DIST_YEAR) + as.factor(DIST_YEAR):log(COMPETITION+0.001) + log(COMPETITION+0.001) + as.factor(STATE) + as.factor(YEAR) + AGE + as.factor(INDUSTRY) + log(POPULATION) + log(POPULATION_SUB+1), data=data)
summary(reg)

# empW -3 sig neg, 0 sig pos
# EMP_RATE almost all sig
# EMP_RATE_SUB almost all sig
# log(empW+1) 0+ sig and pos
reg2 = lm(log(empW+1) ~ as.factor(DIST_YEAR) + as.factor(STATE) + as.factor(YEAR) + AGE + as.factor(INDUSTRY) + log(POPULATION) + log(POPULATION_SUB+1), data=data)
summary(reg2)

# empW only -3 sig
# empRate no significance
# log(empW+1) no significance
reg3 = lm(log(empW+1) ~ as.factor(DIST_YEAR) + as.factor(STATE) + as.factor(YEAR) + log(POPULATION), data=dataAgg)
summary(reg3)

# empW 0.9 significant decreases after 0
# empRate 0.9 has sig pos effects on ends
# empRate_Sub little significance
# log(empW+1) 0.1 sig pos at ends
reg4 = lm(log(empW+1) ~ as.factor(DIST_YEAR) + as.factor(DIST_YEAR):as.factor(COMP_Q) + as.factor(COMP_Q) + as.factor(STATE) + as.factor(YEAR) + log(POPULATION) + log(POPULATION_SUB+1), data=dataAgg2)
summary(reg4)
```

```{r}
library(ggplot2)
est = as.data.frame(summary(reg3)$coef[(2:7),])
est$Time = c(-3,-2,(0:3))
#base = est["as.factor(DIST_YEAR)-1","Estimate"]
ggplot(data=est) +
  geom_line(aes(x=Time,y=Estimate)) +
  geom_errorbar(aes(x=Time,ymin=Estimate-1.96*`Std. Error`, ymax=Estimate+1.96*`Std. Error`)) +

  labs(title="Employment Rate Change, Years Around MW Change")



est = as.data.frame(summary(reg2)$coef[(2:7),])
est$Time = c(-3,-2,(0:3))
#base = est["as.factor(DIST_YEAR)-1","Estimate"]
ggplot(data=est) +
  geom_line(aes(x=Time,y=Estimate)) +
  geom_errorbar(aes(x=Time,ymin=Estimate-1.96*`Std. Error`, ymax=Estimate+1.96*`Std. Error`)) +
  labs(title="Employment Change, Years Around MW Change")

est2 = as.data.frame(summary(reg4)$coef)
index = (0:8)
names(index)=c("0.1","0.2","0.3","0.4","0.5","0.6","0.7","0.8","0.9")

estk = function(k){
  if(k=="0"){
    interact = est2[(2:7),]
  } else {
    start = 57 + 6 * index[k]
    interact = est2[(start:(start+5)),]
  }
  interact$Time = c(-3,-2,0,1,2,3)
  rownames(interact) = NULL
  return(interact)
}
a = 0.05

# ggplot() +
#   geom_line(data=estk("0"), aes(x=Time,y=Estimate), col="blue") + 
#   geom_ribbon(data=estk("0"), aes(x=Time,ymin=Estimate-1.96*`Std. Error`, ymax=Estimate+1.96*`Std. Error`), alpha=a, fill="blue")+
#   geom_line(data=estk("0.2"), aes(x=Time,y=Estimate), col="cyan") + 
#   geom_ribbon(data=estk("0.2"), aes(x=Time,ymin=Estimate-1.96*`Std. Error`, ymax=Estimate+1.96*`Std. Error`), alpha=a, fill="cyan")+
#   geom_line(data=estk("0.4"), aes(x=Time,y=Estimate),col="green") + 
#   geom_ribbon(data=estk("0.4"), aes(x=Time,ymin=Estimate-1.96*`Std. Error`, ymax=Estimate+1.96*`Std. Error`), alpha=a, fill="green")+
#   geom_line(data=estk("0.6"), aes(x=Time,y=Estimate),col="yellow") + 
#   geom_ribbon(data=estk("0.6"), aes(x=Time,ymin=Estimate-1.96*`Std. Error`, ymax=Estimate+1.96*`Std. Error`), alpha=a, fill="yellow")+
#   geom_line(data=estk("0.8"), aes(x=Time,y=Estimate),col="orange") +
#   geom_ribbon(data=estk("0.8"), aes(x=Time,ymin=Estimate-1.96*`Std. Error`, ymax=Estimate+1.96*`Std. Error`), alpha=a, fill="orange")
#   

for(c in c("0",names(index))){
  print(ggplot() +
    geom_line(data=estk(c), aes(x=Time,y=Estimate), col="blue") + 
    geom_ribbon(data=estk(c), aes(x=Time,ymin=Estimate-1.96*`Std. Error`, ymax=Estimate+1.96*`Std. Error`), alpha=a, fill="blue") +
    labs(title=paste0("Competition Level ",c)))
}
```




Event study:
```{r}
rm(list=ls())
library(plm)
library(stargazer)
library(tidyverse)
data = read.csv("IndividualDataConc2Tenths1996.csv")
data$RealMW = data$MW / data$CPI_FACTOR
data$DIST_YEAR = floor(data$DIST/4)
data$DIST_YEAR[data$DIST_YEAR == 249] = -999
data$EMP_RATE = data$empW / data$POPULATION
data$EMP_RATE_SUB = data$empW / data$POPULATION_SUB
data$EMP_RATE_SUB[is.na(data$EMP_RATE_SUB)] = 0

conc = read.csv("Conc Complete.csv")
conc = filter(conc, INDUSTRY=="00", METFIPS <100, AGEGRP=="A00", YEAR <= 2016)
```

```{r}
stargazer(filter(data,YEAR>=2000), type="latex",title="Summary Statistics",style="qje")
```


```{r}
# Events:
events = distinct(data[c("YEAR","QUARTER","STATE","EVENT")])
# edit: 2000 was 2004
events$USABLE = as.numeric(events$EVENT == 1 & events$YEAR >= 2000 & events$YEAR <= 2011)

events$CLEAN = 0
for(state in unique(events$STATE)){
  filt = events$STATE == state
  if(sum(events$EVENT[filt])==0){
    events$CLEAN[filt] = 1
  } else{
    for(i in (1:dim(events[filt,])[1])){
      start = max(1, i - 12)
      end = min(dim(events[filt,])[1], i + 19)
      events$CLEAN[filt][i] = as.numeric(sum(events$EVENT[filt][(start:end)])==0)
    }
  }
}

usable = filter(events, USABLE==1)
for(state in unique(events$STATE)){
  usable[state] = 0
}
for(i in (1:dim(usable)[1])){
  for(state in unique(events$STATE)){
    usable[i,state] = filter(events, STATE==state, YEAR==usable$YEAR[i], QUARTER==usable$QUARTER[i])$CLEAN
  }
}
for(i in (1:dim(usable)[1])){
  usable[i,usable[i,"STATE"]] = 1
}
```


new: add MW_CONTROL
```{r}
# Regressions:
library(stringi)
rm(results)
results = data.frame()

data$MW_CONTROL = as.numeric(data$REAL_CHANGE > 0 & !data$EVENT)
data$MW_CONTROL2 = data$REAL_CHANGE*(1-data$EVENT)

formula = as.formula("EMP_RATE ~ as.factor(DIST_YEAR):as.factor(WAGE_BIN) + as.factor(STATE) + as.factor(YEAR)+as.factor(WAGE_BIN) + MW_CONTROL2 + MW_CONTROL")
for(i in 1:dim(usable)[1]){
  print(i)
  eventState = usable[i,"STATE"]
  states = usable[i,(7:dim(usable)[2])]
  states = colnames(states)[states == 1]
  
  startYear = usable[i,"YEAR"] - 3
  startQuarter = usable[i,"QUARTER"]
  endYear = usable[i,"YEAR"] + 4
  endQuarter = usable[i,"QUARTER"]
  if(endQuarter == 1){
    endQuarter = 4
    endYear = endYear - 1
  } else{
    endQuarter = endQuarter - 1
  }
  
  temp = aggregate(EMP_RATE~YEAR+QUARTER+STATE+DIST_YEAR+WAGE_BIN+MW_CONTROL2+MW_CONTROL,
                   data=filter(data, YEAR > startYear | (YEAR == startYear & QUARTER >= startQuarter), 
                               YEAR < endYear | (YEAR == endYear & QUARTER <= endQuarter), 
                               STATE %in% states), 
                   FUN=sum)
  reg = lm(formula, data=temp)
  coef = summary(reg)$coef
  
  coefk = function(k){
    yeark = rownames(coef)
    yeark = yeark[stri_detect_fixed(yeark,paste0("(DIST_YEAR)",k))]
    coek = data.frame(coef[rownames(coef) %in% yeark,])
    return(coek)
  }
  
  epop = 1/4 * sum(filter(temp, STATE==eventState, DIST_YEAR==-1)$EMP_RATE)
  # add 6 to year to get index for estimates
  a = function(t){
    return((sum(coefk(t)$Estimate[(6:10)]) - sum(coefk(-1)$Estimate[(6:10)]))/epop)
  }
  b = function(t){
    return((sum(coefk(t)$Estimate[(2:5)]) - sum(coefk(-1)$Estimate[(2:5)]))/epop)
  }
  res = c(a(-3),a(-2),a(-1),a(0),a(1),a(2),a(3),b(-3),b(-2),b(-1),b(0),b(1),b(2),b(3))
  results = rbind(results,res)
  
}
colnames(results)=c("a-3","a-2","a-1","a0","a1","a2","a3","b-3","b-2","b-1","b0","b1","b2","b3")
results$aAvg = 1/4*(results$a0 + results$a1 + results$a2 + results$a3)
results$bAvg = 1/4*(results$b0 + results$b1 + results$b2 + results$b3)
results$diff_3 = results$`a-3`+results$`b-3`
results$diff_2 = results$`a-2`+results$`b-2`
results$diff_1 = results$`a-1`+results$`b-1`
results$diff0 = results$a0+results$b0
results$diff1 = results$a1+results$b1
results$diff2 = results$a2+results$b2
results$diff3 = results$a3+results$b3
results$diffAvg = results$aAvg + results$bAvg
results = cbind(usable,results)
```

```{r}
# assign competition (average):
fips = read.csv("FIPS.csv")
fips = fips[(2:(dim(fips)[1]-1)),]
fips$FIPS = as.numeric(fips$FIPS)
results$COMP = NA
results$COMP3 = NA
results$POPULATION = NA
for(i in (1:dim(results)[1])){
  results$COMP[i] = mean(log(filter(data, STATE==results$STATE[i], YEAR==results$YEAR[i], QUARTER==results$QUARTER[i])$COMPETITION +0.001))
  results$COMP3[i] = mean(filter(data, STATE==results$STATE[i], YEAR==results$YEAR[i], QUARTER==results$QUARTER[i])$COMPETITION)
  results$POPULATION[i] = sum(filter(data, STATE==results$STATE[i], YEAR==results$YEAR[i], QUARTER==results$QUARTER[i])$EARNWT)
}


map = fips$FIPS
names(map) = fips$Abbr
results$METFIPS = map[results$STATE]
# NH removed due to lack of concentration data
results = merge(results, conc[c(1,4,5,8)], all.x=T)
results$COMP2 = log(results$COMPETITION) #+0.001


```

```{r}
# checking things about conc data, not needed
conc = filter(conc, METFIPS <100)
summary(conc)
stateConc = c()
for(state in unique(conc$METFIPS)){
  stateConc = c(stateConc, min(filter(conc,METFIPS==state)$YEAR))
}
```


```{r}
library(stargazer)
library(ggplot2)
comp = results$COMP2
reg = lm(diffAvg ~ comp, data=results, weights=POPULATION)
#summary(reg)
#plot(diffAvg ~ comp[!is.na(comp)], data=results[!is.na(comp),])
#lines(comp[!is.na(comp)], reg$fitted.values, type='l')

regA = lm(aAvg ~ comp, data=results, weights=POPULATION)
#summary(regA)
regB = lm(bAvg ~ comp, data=results, weights=POPULATION)
#summary(regB)
#plot(aAvg ~ comp[!is.na(comp)], data=results[!is.na(comp),], col="red")
#points(bAvg ~ comp[!is.na(comp)], data=results[!is.na(comp),], col="blue")
#lines(comp[!is.na(comp)], regA$fitted.values, type='l', col="red")
#lines(comp[!is.na(comp)], regB$fitted.values, type='l', col="blue")
# lesser effect on lost jobs below MW.  Makes sense since almost all should be lost regardless.
# results are robust to each estimate of competition

stargazer(reg, regA, regB, type="text", star.cutoffs=c(0.05,0.01,0.001), style="qje")

plots = results[!is.na(comp),]
plots$reg = reg$fitted.values
plots$regA = regA$fitted.values
plots$regB = regB$fitted.values

ggplot(data=plots, aes(x=COMP2)) +
  geom_point(aes(y=diffAvg)) +
  geom_line(aes(y=reg)) +
  labs(x="Log Competition",y="Change in Jobs per Capita") +
  ylim(-0.11,0.04) +
  theme_classic() +
  theme(panel.grid.major.y=element_line())
#ggsave("EventTotal.jpg", width=10, height=6)

ggplot(data=plots, aes(x=COMP2)) +
  geom_point(aes(y=aAvg, color="Above MW")) +
  geom_line(aes(y=regA, color="Above MW")) +
  geom_point(aes(y=bAvg, color="Below MW")) +
  geom_line(aes(y=regB, color="Below MW")) +
  labs(x="Log Competition", y="Change in Jobs per Capita", color="Legend") +
  scale_color_manual(values=c("Above MW"="blue", "Below MW"="red")) +
  ylim(-0.11,0.04) +
  theme_classic() +
  theme(legend.position=c(0.5,0.15), legend.background=element_blank(), legend.key=element_blank(),
        panel.grid.major.y=element_line(), legend.direction="horizontal") +
  guides(color = guide_legend(title = NULL))

#ggsave("EventSeparate.jpg", width=10, height=6)

```

```{r}
# Event plot:
library(Hmisc)
plots2 = plots#filter(plots, COMPETITION <0.18)
diffs = c(weighted.mean(plots2$diff_3, plots2$POPULATION),
          weighted.mean(plots2$diff_2, plots2$POPULATION),
          weighted.mean(plots2$diff_1, plots2$POPULATION),
          weighted.mean(plots2$diff0, plots2$POPULATION),
          weighted.mean(plots2$diff1, plots2$POPULATION),
          weighted.mean(plots2$diff2, plots2$POPULATION),
          weighted.mean(plots2$diff3, plots2$POPULATION))
sds = sqrt(c(wtd.var(plots2$diff_3, plots2$POPULATION),
          wtd.var(plots2$diff_2, plots2$POPULATION),
          wtd.var(plots2$diff_1, plots2$POPULATION),
          wtd.var(plots2$diff0, plots2$POPULATION),
          wtd.var(plots2$diff1, plots2$POPULATION),
          wtd.var(plots2$diff2, plots2$POPULATION),
          wtd.var(plots2$diff3, plots2$POPULATION)))
eplot = data.frame(cbind((-3:3),diffs,sds))
colnames(eplot)=c("Year","Estimate","SD")
ggplot(data=eplot,aes(x=Year)) +
  geom_line(aes(y=Estimate)) +
  geom_errorbar(aes(ymin=Estimate-2.179*SD, ymax=Estimate+2.179*SD)) +
  theme_classic() +
  theme(panel.grid.major.y=element_line(), panel.grid.minor.y=element_line()) +
  labs(x="Years Since MW Increase", y="Change in Jobs per Capita") +
  ylim(-0.3,0.3)
#ggsave("EventEstimates.jpg", width=10, height=6)
```

log competition SD: 0.148


Events all together (retry):
```{r}
formula = as.formula("EMP_RATE ~ REAL_CHANGE:as.factor(DIST_YEAR):as.factor(WAGE_BIN) + as.factor(STATE):as.factor(WAGE_BIN) + as.factor(YEAR):as.factor(WAGE_BIN) + MW_CONTROL2 + MW_CONTROL")

temp = aggregate(EMP_RATE~YEAR+QUARTER+STATE+DIST_YEAR+WAGE_BIN+MW_CONTROL2+MW_CONTROL+REAL_CHANGE,
                 data=data, FUN=sum)

regT = lm(formula, data=temp)

coef = summary(regT)$coef


coefTK = function(t,k){
  yeart = rownames(coef)
  yeart = yeart[stri_detect_fixed(yeart,paste0("(DIST_YEAR)",t))]
  if(k<10 & k >=0){
    yeart = yeart[stri_detect_fixed(yeart,paste0("(WAGE_BIN)",k)) & str_sub(yeart,-2,-2)==")"]
  } else{
    yeart = yeart[stri_detect_fixed(yeart,paste0("(WAGE_BIN)",k))]
  }
  
  coet = data.frame(coef[rownames(coef) %in% yeart,])
  return(coet["Estimate",])
  
}

changeK = function(k){
  return(1/3*(coefTK(0,k)+coefTK(1,k)+coefTK(2,k))-coefTK(-1,k))
}

change = unlist(lapply((-5:20),changeK))
barplot(change)
```

Summary stats:
```{r}
rm(list=ls())
library(plm)
library(stargazer)
library(tidyverse)
library(ggplot2)
library(maps)
data = read.csv("IndividualDataConc2Tenths1996.csv")
data$RealMW = data$MW / data$CPI_FACTOR
data$DIST_YEAR = floor(data$DIST/4)
data$DIST_YEAR[data$DIST_YEAR == 249] = -999
data$EMP_RATE = data$empW / data$POPULATION
data$EMP_RATE_SUB = data$empW / data$POPULATION_SUB
data$EMP_RATE_SUB[is.na(data$EMP_RATE_SUB)] = 0

conc = read.csv("Conc Complete.csv")
conc = filter(conc, YEAR<= 2016)
conc$Granularity = NA
conc$Granularity[conc$INDUSTRY=="00" & conc$METFIPS<100 & conc$AGEGRP=="A00"]="Coarse"
conc$Granularity[conc$INDUSTRY!="00" & conc$METFIPS>=100 & conc$AGEGRP!="A00"]="Fine"
concState = filter(conc, INDUSTRY=="00", METFIPS <100, AGEGRP=="A00")
concDetailed = filter(conc, INDUSTRY != "00", METFIPS>=100, AGEGRP!="A00")

# ggplot(data=conc[!is.na(conc$G1),]) +
#   geom_density(aes(x=log(COMPETITION+0.001),color=G1,fill=G1),alpha=0.5) +
#   theme_classic()
# 
# ggplot(data=conc[!is.na(conc$G1),]) +
#   geom_violin(aes(x=G1, y=log(COMPETITION+0.001),fill=G1)) +
#   theme_classic() +
#   labs(x=" ",y="Log Competition") +
#   theme(legend.position=c(0.9,0.2), legend.background=element_blank(), legend.key=element_blank(),
#         panel.grid.major.y=element_line())

ggplot(data=conc[!is.na(conc$Granularity) & conc$COMPETITION>0,]) +
  geom_violin(aes(x=Granularity, y=log(COMPETITION),fill=Granularity)) +
  theme_classic() +
  labs(x=" ",y="Log Competition") +
  theme(legend.position="none", legend.background=element_blank(), legend.key=element_blank(),
        panel.grid.major.y=element_line())
ggsave("ConcDistribution.jpg", width=10, height=6)

# onePeriod = filter(concState,YEAR==2010,QUARTER==4)
# map("state",fill=T,col=gray(onePeriod$COMPETITION/max(onePeriod$COMPETITION)))
# 
# twoPeriod = filter(conc, YEAR==2010, QUARTER==4, INDUSTRY=="00",AGEGRP=="A00")
# map("county",fill=T, col=gray((log(twoPeriod$COMPETITION+0.001)-min(log(twoPeriod$COMPETITION+0.001)))/(max(log(twoPeriod$COMPETITION+0.001))-min(log(twoPeriod$COMPETITION+0.001)))))
# map("state",fill=T, col=gray((log(onePeriod$COMPETITION+0.001)-min(log(twoPeriod$COMPETITION+0.001)))/(max(log(twoPeriod$COMPETITION+0.001))-min(log(twoPeriod$COMPETITION+0.001)))))
```

